# Generated by Django 4.2.5 on 2023-09-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='reply',
            field=models.CharField(default='', max_length=200),
        ),
    ]
