# Generated by Django 4.2.5 on 2023-09-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artapp', '0002_alter_complaint_complaint_alter_complaint_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
