# Generated by Django 4.2.5 on 2023-09-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artapp', '0003_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.IntegerField(default='', max_length=30),
        ),
    ]
