# Generated by Django 4.2.5 on 2023-10-06 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artapp', '0005_alter_rating_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='LOGIN',
        ),
    ]
