# Generated by Django 4.2.5 on 2023-10-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artapp', '0006_remove_product_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='expiration_date',
            field=models.DateField(),
        ),
    ]
